package com.webserver.examples;

import com.webserver.core.HttpRequest;
import com.webserver.core.HttpResponse;
import com.webserver.servlet.Servlet;

/**
 * Example servlet - handles /hello requests
 */
public class HelloServlet implements Servlet {

    @Override
    public void init() {
        System.out.println("[HelloServlet] Initialized");
    }

    @Override
    public void service(HttpRequest request, HttpResponse response) throws Exception {
        System.out.println("[HelloServlet] Processing request");

        // Get parameter from query string
        String name = request.getParameter("name");
        if (name == null) {
            name = "World";
        }

        // Build HTML response
        response.write("<html>");
        response.write("<head><title>Hello Servlet</title></head>");
        response.write("<body style='font-family: Arial; padding: 20px;'>");
        response.write("<h1>Hello, " + name + "!</h1>");
        response.write("<p>This response was generated by <code>HelloServlet</code></p>");
        response.write("<p>Request details:</p>");
        response.write("<ul>");
        response.write("<li><b>Method:</b> " + request.getMethod() + "</li>");
        response.write("<li><b>URI:</b> " + request.getUri() + "</li>");
        response.write("<li><b>Path:</b> " + request.getPath() + "</li>");
        response.write("<li><b>Query:</b> " + request.getQueryString() + "</li>");
        response.write("</ul>");
        response.write("<p>Try: <a href='/hello?name=Alice'>/hello?name=Alice</a></p>");
        response.write("</body>");
        response.write("</html>");
    }

    @Override
    public void destroy() {
        System.out.println("[HelloServlet] Destroyed");
    }
}
